# Generated by Django 3.1.5 on 2021-02-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_city_contry_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='contry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.contry'),
        ),
    ]
