# Generated by Django 3.1.6 on 2021-02-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210211_0101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contry',
            new_name='Country',
        ),
    ]
